// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __vector__handler_hh__
#define __vector__handler_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_vector__handler
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_vector__handler
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_vector__handler
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





#ifndef __Vector__Ops__
#define __Vector__Ops__

class Vector_Ops;
class _objref_Vector_Ops;
class _impl_Vector_Ops;

typedef _objref_Vector_Ops* Vector_Ops_ptr;
typedef Vector_Ops_ptr Vector_OpsRef;

class Vector_Ops_Helper {
public:
  typedef Vector_Ops_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_Vector_Ops, Vector_Ops_Helper> Vector_Ops_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_Vector_Ops,Vector_Ops_Helper > Vector_Ops_out;

#endif

// interface Vector_Ops
class Vector_Ops {
public:
  // Declarations for this interface type.
  typedef Vector_Ops_ptr _ptr_type;
  typedef Vector_Ops_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(::CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
  
  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.
  struct Vector {
    typedef _CORBA_ConstrType_Fix_Var<Vector> _var_type;

    
    ::CORBA::Long x;

    ::CORBA::Long y;

  

    void operator>>= (cdrStream &) const;
    void operator<<= (cdrStream &);
  };

  typedef Vector::_var_type Vector_var;

  typedef Vector& Vector_out;


};

class _objref_Vector_Ops :
  public virtual ::CORBA::Object,
  public virtual omniObjRef
{
public:
  Vector_Ops::Vector Add(const ::Vector_Ops::Vector& a, const ::Vector_Ops::Vector& b);

  inline _objref_Vector_Ops()  { _PR_setobj(0); }  // nil
  _objref_Vector_Ops(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_Vector_Ops();

  
private:
  virtual void* _ptrToObjRef(const char*);

  _objref_Vector_Ops(const _objref_Vector_Ops&);
  _objref_Vector_Ops& operator = (const _objref_Vector_Ops&);
  // not implemented

  friend class Vector_Ops;
};

class _pof_Vector_Ops : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_Vector_Ops() : _OMNI_NS(proxyObjectFactory)(Vector_Ops::_PD_repoId) {}
  virtual ~_pof_Vector_Ops();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_Vector_Ops :
  public virtual omniServant
{
public:
  virtual ~_impl_Vector_Ops();

  virtual Vector_Ops::Vector Add(const ::Vector_Ops::Vector& a, const ::Vector_Ops::Vector& b) = 0;
  
public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();
  
};




class POA_Vector_Ops :
  public virtual _impl_Vector_Ops,
  public virtual ::PortableServer::ServantBase
{
public:
  virtual ~POA_Vector_Ops();

  inline ::Vector_Ops_ptr _this() {
    return (::Vector_Ops_ptr) _do_this(::Vector_Ops::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr



inline void
Vector_Ops::_marshalObjRef(::Vector_Ops_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_vector__handler
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_vector__handler
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_vector__handler
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_vector__handler
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_vector__handler
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_vector__handler
#endif

#endif  // __vector__handler_hh__

